include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "ios/build/**"
    - "android/build/**"
    - "ios/Pods/**"

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
